### ISSUE TITLE
the data generated by outpainting has obvious discontinuous traces at the mask boundary.

### ISSUE THREAD

**Issue by Lucy-IM** [thuanz123/realfill#10]
Hello author, your work is really great. When studying your work, I found that using the parameters and test data provided by the author, the data generated by extrapolation has obvious discontinuous traces at the mask boundary. Is there any way to eliminate it.

I really hope to receive your letter.

**Comment by Lucy-IM** [comment]
![0](https://github.com/thuanz123/realfill/assets/50547766/ef4a9e6b-6ec0-43ea-8b0a-5ff9334c9bf2)

**Comment by Lucy-IM** [comment]
![Uploading 0.png…]()

**Comment by thuanz123** [comment]
First of all, I have to say that I'm not related to the author in any way and this is an unofficial implementation. 

Secondly, yeah it is because the way I blend the original masked image with the output of the model is very naive so sometimes it will show a small white boundary

**Comment by Lucy-IM** [comment]
Thank you very much for receiving your answer！ @thuanz123.

**Comment by Lanxin1011** [comment]
Thank you so much for providing this implementation @thuanz123!!!. The fundamental reason for the small white boundary might be the irregular value of the mask, the same as I've encountered in an inpainting work. I checked the value of the mask image in '/data' and found the mask values have other values apart from 0 and 255 at the boundary of the masked region, which may result in blurry edges or the above white boundary.

**Comment by thuanz123** [comment]
Thks @Lanxin1011!!! After using correct mask, the issue seems gone so I think I can safely close this issue now. Simply correcting the mask and the masked image does the trick here
