### ISSUE TITLE
Is it possible to adjust this approach for image restoration?

### ISSUE THREAD

**Issue by MrGTAmodsgerman** [thuanz123/realfill#11]
Is it technically possible to adjust that paper to denoise, upscale or maybe colorize images by using references? 
Like if i would have a noisy scanned negative from a room, where i have a image of the same scene without much differences from a true digital era image that is way better. Or a higher resolution version of that scene to upscale the target the correct way.

**Comment by thuanz123** [comment]
I think [this work](https://personalized-restoration.github.io/) is a better suit for what you want since your task requires a model that can generate a whole clean image. Here, RealFill is only suitable for inpainting.
