### ISSUE TITLE
Weighting for MSE Loss

### ISSUE THREAD

**Issue by mvp18** [thuanz123/realfill#12]
Hi,

Thanks for your work. I had one question about the weighting variable used for the MSE loss for noise residuals with reference/target images. 

Since you define it as

```
weighting = Image.new("L", image.size)
```

or as the mask of a target image, the condition

```
example["weightings"] = weighting < 0
```

would zero out the loss for both reference and target images as weighting becomes zero for the latent space after interpolation from the pixel space. As the masks are either 0 or 1, the weightings tensor would be 0 everywhere. I think the correct condition would be 

```
example["weightings"] = weighting <= 0
```

Please correct me if I am wrong.

**Comment by thuanz123** [comment]
Hi @mvp18, sorry for my late reply. After [self.transform](https://github.com/thuanz123/realfill/blob/main/train_realfill.py#L473) is applied, the range for image and weighting is [-1, 1], not [0, 1] anymore. So the code is still correct
