### ISSUE TITLE
Version of transformers

### ISSUE THREAD

**Issue by ScienceLi1125** [thuanz123/realfill#13]
Hi! I have some troubles when training the realfill.
When I used the latest version of transformers, something went wrong:`OSError: stabilityai/stable-diffusion-2-inpainting does not appear to have a file named tokenizer/config.json`. 
I found some suggestions [here](https://github.com/CompVis/stable-diffusion/issues/302#issuecomment-1260029102) and re-installed `transformers==4.22.1`, but another bug occured:`ImportError: cannot import name 'CLIPTextModelWithProjection' from 'transformers`. May I ask which version of transformers could work in realfill?
Thanks a lot!

**Comment by thuanz123** [comment]
Hi @ScienceLi1125, the requirements.txt file is actually wrong. my conda env is following:
- diffusers == 0.27.1
- accelerate == 0.28.0
- transformers == 4.35.2
- peft == 0.6.2
- torch == 2.2.1+cu118
- torchvision == 0.17.1+cu118
