### ISSUE TITLE
[suggestion] scene variants example

### ISSUE THREAD

**Issue by msskaa12** [thuanz123/realfill#18]
Hi. Thank you for your code! I had read the orignal paper  it say :

Figure 9. RealFill is able to generate multiple scene variants when conditioned on a blank image as input, e.g., people are added or removed in the first and second rows. This suggests that the finetuned model can relate the elements inside the scene in a compositional manner.

I am comfusing what the black image meaning , could you also give a exmaple about this case , thank you your reply

<img width="414" alt="image" src="https://github.com/thuanz123/realfill/assets/78275037/96146d24-3fd7-4cdd-81c8-34fd878e9a2b">

**Comment by thuanz123** [comment]
What they mean is that if the conditioning image is completely masked, i.e. a blank image, then the model is still able to generate images that resemble the target scene. This seems correct from some of my limited experiments.

________________________________
From: msskaa12 ***@***.***>
Sent: Wednesday, April 17, 2024 3:14 PM
To: thuanz123/realfill ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [thuanz123/realfill] [suggestion] scene variants example (Issue #18)


Hi. Thank you for your code! I had read the orignal paper it say :

Figure 9. RealFill is able to generate multiple scene variants when conditioned on a blank image as input, e.g., people are added or removed in the first and second rows. This suggests that the finetuned model can relate the elements inside the scene in a compositional manner.

I am comfusing what the black image meaning , could you also give a exmaple about this case , thank you your reply

image.png (view on web)<https://github.com/thuanz123/realfill/assets/78275037/96146d24-3fd7-4cdd-81c8-34fd878e9a2b>
