### ISSUE TITLE
Why is Use "accelerate launch train_realfill.py" super slower than directly use "python "

### ISSUE THREAD

**Issue by zj19921221** [thuanz123/realfill#2]
Have you ever tested how long it takes to train an image? Also, why is the max_train_steps set to 2000 when it was previously set to 400?

**Comment by thuanz123** [comment]
> Why is Use "accelerate launch train_realfill.py" super slower than directly use "python "

I'm not sure, this is problem of accelerate, you can ask them

> Have you ever tested how long it takes to train an image? 

About 1 hour on a 32GB V100

> Also, why is the max_train_steps set to 2000 when it was previously set to 400?

It is just what the author use in the paper, you can change to whatever you like

**Comment by zj19921221** [comment]
When will the inference code be available? I'm really looking forward to it~

thanks～

**Comment by zj19921221** [comment]
> > Why is Use "accelerate launch train_realfill.py" super slower than directly use "python "
> 
> I'm not sure, this is problem of accelerate, you can ask them
> 
> > Have you ever tested how long it takes to train an image?
> 
> About 1 hour on a 32GB V100
> 
> > Also, why is the max_train_steps set to 2000 when it was previously set to 400?
> 
> It is just what the author use in the paper, you can change to whatever you like

thanks～

**Comment by thuanz123** [comment]
> When will the inference code be available? I'm really looking forward to it~
> 
> thanks～

inference code is super simple actually, I just add it in

**Comment by zj19921221** [comment]
> > When will the inference code be available? I'm really looking forward to it~
> > thanks～
> 
> inference code is super simple actually, I just add it in

May I ask, in the inference script, does "model_path" refer to the address of lora after training, or the address of the original stable-diffusion inpainting? If it is the address of lora, an error will be reported: 「OSError: Error no file named config.json found in directory /home/nick.zj/pro/realfill-main/flowerwoman-model.」

**Comment by thuanz123** [comment]
Oh sorry, I didn't commit some fix. After update the new code and run the training again, you should be able to use the inference code

**Comment by zj19921221** [comment]
> Oh sorry, I didn't commit some fix. After update the new code and run the training again, you should be able to use the inference code

Okay, I'll re-pull the latest training code and retrain it. 
Which path should I use for the model_path in the inference script? Is it the one after training?

**Comment by zj19921221** [comment]
I make it~ thanks~
