### ISSUE TITLE
AttributeError: module 'torchvision.transforms.v2' has no attribute 'ToImageTensor'

### ISSUE THREAD

**Issue by thrakazog** [thuanz123/realfill#20]
I'm running the torchvision==0.17.1 specified in the requirements.txt document but that seems to be missing a required attribute.  Is there another version of tourch/tourchvision that I should be targeting?

Traceback (most recent call last):
  File "train_realfill.py", line 955, in <module>
    main(args)
  File "train_realfill.py", line 695, in main
    train_dataset = RealFillDataset(
  File "train_realfill.py", line 449, in __init__
    transforms_v2.ToImageTensor(),
AttributeError: module 'torchvision.transforms.v2' has no attribute 'ToImageTensor'

**Comment by thuanz123** [comment]
hmm strange, I guess you can try this
torch                     2.0.1
torchvision               0.15.2

**Comment by dae-sun** [comment]
If you are using latest version, 
try
`transforms_v2.PILToTensor()`

**Comment by thuanz123** [comment]
Hi @thrakazog , due to some breaking changes of pytorch. Either you change the code to transforms_v2.PILToTensor() like @dae-sun said or try the old environment [setup ](https://github.com/thuanz123/realfill/blob/15748e4bfc004d3fb4dcb188e6bf13aeb8c2feb8/requirements.txt) that I just updated
