### ISSUE TITLE
The Loss calculation is always 0

### ISSUE THREAD

**Issue by yjyuanjin** [thuanz123/realfill#23]
According to the paper, the loss of the reference image needs to be calculated in full, and the loss of the target image only calculates the area that is not masked. In the program, all weighting values ​​are 0. In fact, weights need to be all 1 in the reference image and 1 in the target image where mask=0.

**Comment by thuanz123** [comment]
I admit that the code is a bit weird but weighting is correct and you can take a look at #12 to see more in detail about the weighting
