### ISSUE TITLE
process on the border of mask and original images

### ISSUE THREAD

**Issue by xinli2008** [thuanz123/realfill#3]
sorry to bother you again.
I notice that you process the border of dataset masks and original images during inference:
![image](https://github.com/thuanz123/realfill/assets/71311087/46418d6e-3c86-4680-8597-931c7022e8c9)
I do the process according to paper, but output bad results! would you like to provide the process code ?
Best

**Comment by thuanz123** [comment]
the mask is only process **after** the inference **not** during. I will try to add a simple code for this but there is only three steps:

1. run the code infer.py normally and select the best output as you like
2. blur the input mask
3. blend the original masked image and the output chosen in step 1 using the blur mask in step 2

**Comment by xinli2008** [comment]
thank you for your kindly reply and i will try the blur trick code.
wIsh you have a nice weekend

**Comment by thuanz123** [comment]
hi @xinli2008, I just add the blurring trick in the infer.py code and improve the training of realfill. Now you just need to do the training and run inference. All tricks in the paper have been added except the "Correspondence-Based Seed Selection" trick in sec 4.2 which is only used for evaluation

**Comment by AIMads** [comment]
Hey I get this error when running the inference script:

  File "/home/humaid/Desktop/realfill/infer.py", line 83, in <module>
    result = Image.composite(result, image, mask_image)
  File "/home/humaid/mambaforge/envs/realfill/lib/python3.10/site-packages/PIL/Image.py", line 3363, in composite
    image.paste(image1, None, mask)
  File "/home/humaid/mambaforge/envs/realfill/lib/python3.10/site-packages/PIL/Image.py", line 1738, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
