### ISSUE TITLE
How to make target mask

### ISSUE THREAD

**Issue by AIMads** [thuanz123/realfill#6]
Hey the target in the example data, how do you make the mask?

**Comment by thuanz123** [comment]
Whatever image masking tool that you like. Just try to be the same format as in the example

**Comment by AIMads** [comment]
Just tried with mine doesnt work, do you have one you can share?

**Comment by thuanz123** [comment]
If you dont mind, can you show what doesn't work for you? Back then I just use a simple python code using OpenCV to create mask. Also, I don't think the mask can harm the final quality as long as it is in the correct format

**Comment by AIMads** [comment]
# import the necessary packages
import numpy as np
import argparse
import cv2
# construct the argument parser and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", type=str, default="00048-2961545495.png",
	help="path to the input image")
args = vars(ap.parse_args())

# load the original input image and display it to our screen
image = cv2.imread(args["image"])
cv2.imshow("Original", image)
# a mask is the same size as our image, but has only two pixel
# values, 0 and 255 -- pixels with a value of 0 (background) are
# ignored in the original image while mask pixels with a value of
# 255 (foreground) are allowed to be kept
mask = np.zeros(image.shape[:2], dtype="uint8")
cv2.rectangle(mask, (200, 256), (924, 1240), 255, -1)
cv2.imshow("Rectangular Mask", mask)
# apply our mask -- notice how only the person in the image is
# cropped out
masked = cv2.bitwise_and(image, image, mask=mask)
cv2.imshow("Mask Applied to Image", masked)
cv2.imwrite("image.jpg",masked)
cv2.imwrite("mask.png",mask)
cv2.waitKey(0)

**Comment by thuanz123** [comment]
I think your code is almost correct except the way you save the mask is not in correct format. Keep everything the same except the line cv2.imwrite("mask.png", mask) you change to cv2.imwrite("mask.png", 255 - mask)

**Comment by thuanz123** [comment]
You can see in the example pixels with a value of 255 (white color) are ignored in the original image while mask pixels with a value of 0 (black color) are allowed to be kept

Example Mask
![image](https://github.com/thuanz123/realfill/assets/32274287/742fed63-c9c0-4bf8-b5e5-fa67ed9e1a99)

Example Masked Image
![target](https://github.com/thuanz123/realfill/assets/32274287/5b5f00db-ea46-4e68-863b-b0df979957b3)

**Comment by AIMads** [comment]
Aaah yes okay yeah that fixes it for the mask, but still need to make the fix for the actual image ;)

**Comment by thuanz123** [comment]
The format in the example is a bit counter-intuitive but that is the fault of the pretrained models 🤣. So I'll close this issue

**Comment by AIMads** [comment]
I fixed it all, so here is a script, it is ugly as hell but it makes the right format xD

import numpy as np
import argparse
import cv2

ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", type=str, default="00048-2961545495.png",
        help="path to the input image")
args = vars(ap.parse_args())

image = cv2.imread(args["image"])
cv2.imshow("Original", image)

mask = np.zeros(image.shape[:2], dtype="uint8")

cv2.rectangle(mask, (200, 256), (924, 1240), 255, -1)
cv2.imshow("Rectangular Mask", mask)

masked = cv2.bitwise_and(image, image, mask=mask)

cv2.imshow("Mask Applied to Image", masked)

cv2.imwrite("image.jpg", 255-masked+masked+masked)
cv2.imwrite("mask.png", 255 - mask)
cv2.waitKey(0)

**Comment by AIMads** [comment]
Hey it still doesnt work 😬
